using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;

// Entry point for C# → UASM compilation of a single UdonSharpBehaviour class.
//
// Emit pipeline:
//   1. EmitFields()       — declare exported/synced/private fields as UASM variables
//   2. EmitMethods()      — register all methods (Udon events, user methods, inherited)
//   3. EmitMethod()       — per method: walk IOperation tree via handler dispatch
//   4. EmitFieldInits()   — emit _start preamble for field initializers
//
// Handler dispatch: each IOperation is routed to the first handler that claims it
// (_stmtHandlers for statements, _exprHandlers for expressions). Handlers call back
// into VisitOperation/VisitExpression for recursive descent.
public class UasmEmitter
{
    readonly EmitContext _ctx;
    readonly IOperationHandler[] _stmtHandlers;
    readonly IExpressionHandler[] _exprHandlers;

    HashSet<IMethodSymbol> _inheritedMethods = new(SymbolEqualityComparer.Default);


    public IReadOnlyList<EmitDiagnostic> Diagnostics => _ctx.Diagnostics;

    static Dictionary<string, string> UdonEventNames => LayoutPlanner.UdonEventNames;
    public UasmEmitter(Compilation compilation, INamedTypeSymbol classSymbol, LayoutPlanner planner = null)
    {
        _ctx = new EmitContext(compilation, classSymbol, planner ?? new LayoutPlanner(compilation));

        var stmtHandler = new StatementHandler(_ctx);
        var loopHandler = new LoopHandler(_ctx);
        var assignHandler = new AssignmentHandler(_ctx);
        var operatorHandler = new OperatorHandler(_ctx);

        _stmtHandlers = new IOperationHandler[] { stmtHandler, loopHandler, assignHandler };
        _exprHandlers = new IExpressionHandler[]
        {
            new ExpressionHandler(_ctx),
            (IExpressionHandler)assignHandler,
            operatorHandler,
            new InvocationHandler(_ctx),
            new ArrayHandler(_ctx),
            new NullableHandler(_ctx),
        };

        _ctx.InitializeDispatchers(VisitOperation, VisitExpression, operatorHandler.EmitPatternCheckImpl);
    }

    // Type name resolution helper: delegates to ExternResolver with the current instance's type param map.
    // Safe to call when _ctx.TypeParamMap is null (falls through to non-map overload).
    string GetUdonType(ITypeSymbol type) => ExternResolver.GetUdonTypeName(type, _ctx.TypeParamMap);
    string GetArrayType(IArrayTypeSymbol arrType) => GetUdonType(arrType);
    string GetArrayElemType(IArrayTypeSymbol arrType)
    {
        var t = GetArrayType(arrType);
        return t.Substring(0, t.Length - "Array".Length);
    }

    void AddExternChecked(string externSig, IOperation sourceOp = null)
    {
        _ctx.AddExternChecked(externSig);
    }

    public string Emit()
    {
        _ctx.Module.SetHeader($"Generated by USugar");
        EnsurePlannerReady();
        EmitFields();
        SetReflectionValues();
        EmitMethods();
        FlushVariablesToModule();
        _ctx.Module.Optimize();
        SyncOptimizerConsts();
        return _ctx.Module.BuildUasmStr();
    }

    void SetReflectionValues()
    {
        var typeName = _ctx.ClassSymbol.ToDisplayString();
        long typeId = ComputeTypeId(typeName);
        _ctx.Vars.SetReflectionValues(typeId, typeName);

        var ancestorIds = CollectAncestorTypeIds(_ctx.ClassSymbol);
        if (ancestorIds.Length > 1)
            _ctx.Vars.DeclareReflTypeIds(ancestorIds);
    }

    static long[] CollectAncestorTypeIds(INamedTypeSymbol type)
    {
        var ids = new List<long>();
        var current = type;
        while (current != null && current.Name != "UdonSharpBehaviour")
        {
            ids.Add(ComputeTypeId(current.ToDisplayString()));
            current = current.BaseType;
        }
        return ids.ToArray();
    }

    internal static long ComputeTypeId(string typeName)
    {
        using var sha = System.Security.Cryptography.SHA256.Create();
        var hash = sha.ComputeHash(System.Text.Encoding.UTF8.GetBytes(typeName));
        return System.BitConverter.ToInt64(hash, 0);
    }

    /// <summary>
    /// Ensures the LayoutPlanner has planned all UdonSharpBehaviour types
    /// and is frozen before the emit phase begins. When using the orchestrator,
    /// this is already done; for standalone usage (tests), it auto-plans.
    /// </summary>
    void EnsurePlannerReady()
    {
        if (_ctx.Planner.IsFrozen) return;
        // Plan all UdonSharpBehaviour types and user-defined interfaces in the compilation
        foreach (var tree in _ctx.Compilation.SyntaxTrees)
        {
            var model = _ctx.Compilation.GetSemanticModel(tree);
            var root = tree.GetRoot();
            foreach (var classDecl in root.DescendantNodes()
                .OfType<ClassDeclarationSyntax>())
            {
                var symbol = model.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
                if (symbol == null || !ExternResolver.IsUdonSharpBehaviour(symbol)) continue;
                _ctx.Planner.Plan(symbol);
                foreach (var iface in symbol.AllInterfaces)
                    _ctx.Planner.Plan(iface);
            }
            foreach (var ifaceDecl in root.DescendantNodes()
                .OfType<Microsoft.CodeAnalysis.CSharp.Syntax.InterfaceDeclarationSyntax>())
            {
                var ifaceSymbol = model.GetDeclaredSymbol(ifaceDecl) as INamedTypeSymbol;
                if (ifaceSymbol != null)
                    _ctx.Planner.Plan(ifaceSymbol);
            }
        }
        _ctx.Planner.Freeze();
    }

    public uint GetHeapSize() => _ctx.Module.GetHeapSize();

    public VariableTable Variables => _ctx.Vars;

    void EmitFields()
    {
        foreach (var member in _ctx.ClassSymbol.GetMembers().OfType<IFieldSymbol>())
        {
            if (member.IsStatic || member.IsImplicitlyDeclared) continue;
            var udonType = GetUdonType(member.Type);
            var flags = VarFlags.None;
            if (member.DeclaredAccessibility == Accessibility.Public
                || member.GetAttributes().Any(a => a.AttributeClass?.Name is "SerializeField" or "SerializeFieldAttribute"))
                flags |= VarFlags.Export;
            string syncMode = null;
            var syncAttr = member.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "UdonSyncedAttribute");
            if (syncAttr != null)
            {
                flags |= VarFlags.Sync;
                if (syncAttr.ConstructorArguments.Length > 0 && syncAttr.ConstructorArguments[0].Value is int modeVal)
                    syncMode = modeVal switch { 2 => "linear", 3 => "smooth", _ => "none" };
                else
                    syncMode = "none";

                // Validate syncable type (enums use their underlying int type)
                var syncCheckType = (member.Type is INamedTypeSymbol nt && nt.TypeKind == TypeKind.Enum)
                    ? GetUdonType(nt.EnumUnderlyingType)
                    : udonType;
                if (!ExternResolver.IsSyncableType(syncCheckType))
                    throw new System.NotSupportedException(
                        $"Cannot sync field '{member.Name}': type '{member.Type}' is not supported by Udon sync");
            }

            // Try to resolve constant field initializers into data section defaults
            // (avoids runtime init code in _start, which runs AFTER _onEnable)
            string constDefault = null;
            object heapValue = null;
            var syntaxRef = member.DeclaringSyntaxReferences.FirstOrDefault();
            if (syntaxRef?.GetSyntax() is VariableDeclaratorSyntax { Initializer: not null } declarator)
            {
                var model = _ctx.Compilation.GetSemanticModel(declarator.SyntaxTree);
                var initOp = model.GetOperation(declarator.Initializer.Value);
                if (initOp != null)
                {
                    var constVal = initOp.ConstantValue;
                    if (constVal.HasValue && constVal.Value != null)
                    {
                        // Constant value — set directly in data section
                        constDefault = FormatConstForDataSection(udonType, constVal.Value, member.Type);
                    }
                    if (constDefault == null)
                    {
                        heapValue = TryEvaluateFieldInitForHeap(initOp, member.Type);
                        if (heapValue == null)
                            _ctx.FieldInitOps.Add((member.Name, initOp, member.Type));
                    }
                }
            }
            _ctx.Vars.DeclareField(member.Name, udonType, flags, constDefault, syncMode);
            if (heapValue != null)
                _ctx.Vars.SetConstValue(member.Name, heapValue);

            // Detect [FieldChangeCallback("PropertyName")]
            var fcbAttr = member.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "FieldChangeCallbackAttribute");
            if (fcbAttr != null && fcbAttr.ConstructorArguments.Length > 0
                && fcbAttr.ConstructorArguments[0].Value is string propName)
            {
                _ctx.FieldChangeCallbacks[member.Name] = propName;
                // Declare _old_ variable (same type) for storing previous value
                _ctx.Vars.DeclareField($"__old_{member.Name}", udonType);
            }
        }

        // Properties → declare as heap variables.
        // Auto-properties use this as primary storage.
        // Non-auto public properties also need a heap var for cross-behaviour
        // GetProgramVariable access (UdonSharp compatibility).
        foreach (var prop in _ctx.ClassSymbol.GetMembers().OfType<IPropertySymbol>())
        {
            if (prop.IsStatic || prop.IsImplicitlyDeclared) continue;
            var isAuto = prop.GetMethod?.IsImplicitlyDeclared == true || prop.SetMethod?.IsImplicitlyDeclared == true;
            if (!isAuto && prop.DeclaredAccessibility != Accessibility.Public) continue;
            var udonType = GetUdonType(prop.Type);
            var flags = VarFlags.None;
            if (prop.DeclaredAccessibility == Accessibility.Public) flags |= VarFlags.Export;
            _ctx.Vars.DeclareField(prop.Name, udonType, flags);
        }

        // Collect declared member names to skip overridden/shadowed members in base classes
        var declaredMemberNames = new HashSet<string>(
            _ctx.ClassSymbol.GetMembers()
                .Where(m => m is IFieldSymbol or IPropertySymbol && !m.IsStatic && !m.IsImplicitlyDeclared)
                .Select(m => m.Name));

        // Inherited fields and properties from user-defined base classes
        var baseType = _ctx.ClassSymbol.BaseType;
        while (baseType != null)
        {
            if (USugarCompilerHelper.IsFrameworkNamespace(baseType.ContainingNamespace) || baseType.Name == "UdonSharpBehaviour") break;
            foreach (var member in baseType.GetMembers().OfType<IFieldSymbol>())
            {
                if (member.IsStatic || member.IsImplicitlyDeclared) continue;
                if (declaredMemberNames.Contains(member.Name)) continue;
                var udonType = GetUdonType(member.Type);
                string constDefault = null;
                var syntaxRef2 = member.DeclaringSyntaxReferences.FirstOrDefault();
                if (syntaxRef2?.GetSyntax() is VariableDeclaratorSyntax { Initializer: not null } decl)
                {
                    var model = _ctx.Compilation.GetSemanticModel(decl.SyntaxTree);
                    var initOp = model.GetOperation(decl.Initializer.Value);
                    if (initOp != null)
                    {
                        var constVal = initOp.ConstantValue;
                        if (constVal.HasValue && constVal.Value != null)
                            constDefault = FormatConstForDataSection(udonType, constVal.Value, member.Type);
                        if (constDefault == null)
                            _ctx.FieldInitOps.Add((member.Name, initOp, member.Type));
                    }
                }
                declaredMemberNames.Add(member.Name);
                var baseFlags = VarFlags.None;
                if (member.DeclaredAccessibility == Accessibility.Public
                    || member.GetAttributes().Any(a => a.AttributeClass?.Name is "SerializeField" or "SerializeFieldAttribute"))
                    baseFlags |= VarFlags.Export;
                _ctx.Vars.DeclareField(member.Name, udonType, baseFlags, constDefault);

                // Inherit FieldChangeCallback from base class fields
                var baseFcbAttr = member.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.Name == "FieldChangeCallbackAttribute");
                if (baseFcbAttr != null && baseFcbAttr.ConstructorArguments.Length > 0
                    && baseFcbAttr.ConstructorArguments[0].Value is string basePropName)
                {
                    _ctx.FieldChangeCallbacks[member.Name] = basePropName;
                    _ctx.Vars.DeclareField($"__old_{member.Name}", udonType);
                }
            }
            foreach (var prop in baseType.GetMembers().OfType<IPropertySymbol>())
            {
                if (prop.IsStatic || prop.IsImplicitlyDeclared) continue;
                if (declaredMemberNames.Contains(prop.Name)) continue;
                var isAuto = prop.GetMethod?.IsImplicitlyDeclared == true || prop.SetMethod?.IsImplicitlyDeclared == true;
                if (!isAuto && prop.DeclaredAccessibility != Accessibility.Public) continue;
                var udonType = GetUdonType(prop.Type);
                var flags = VarFlags.None;
                if (prop.DeclaredAccessibility == Accessibility.Public) flags |= VarFlags.Export;
                declaredMemberNames.Add(prop.Name);
                _ctx.Vars.DeclareField(prop.Name, udonType, flags);
            }
            baseType = baseType.BaseType;
        }
    }

    void EmitMethods()
    {
        var directMethods = _ctx.ClassSymbol.GetMembers().OfType<IMethodSymbol>()
            .Where(m => (m.MethodKind == MethodKind.Ordinary
                      || m.MethodKind == MethodKind.ExplicitInterfaceImplementation
                      || m.MethodKind == MethodKind.PropertyGet
                      || m.MethodKind == MethodKind.PropertySet)
                     && !m.IsImplicitlyDeclared)
            .ToArray();

        // Collect inherited methods from user-defined base classes that are not overridden.
        // In Udon VM each class compiles to a standalone program, so inherited methods
        // must be emitted as part of the derived class's program.
        var overriddenMethods = new HashSet<IMethodSymbol>(SymbolEqualityComparer.Default);
        foreach (var m in directMethods)
        {
            var cur = m.OverriddenMethod;
            while (cur != null)
            {
                overriddenMethods.Add(cur);
                cur = cur.OverriddenMethod;
            }
        }
        var inheritedMethodsList = new List<IMethodSymbol>();
        var inheritBase = _ctx.ClassSymbol.BaseType;
        while (inheritBase != null && inheritBase.Name != "UdonSharpBehaviour")
        {
            if (!inheritBase.DeclaringSyntaxReferences.IsEmpty)
            {
                foreach (var bm in inheritBase.GetMembers().OfType<IMethodSymbol>()
                    .Where(m => (m.MethodKind == MethodKind.Ordinary
                              || m.MethodKind == MethodKind.PropertyGet
                              || m.MethodKind == MethodKind.PropertySet)
                             && !m.IsImplicitlyDeclared && !m.IsGenericMethod && !m.IsAbstract))
                {
                    if (!overriddenMethods.Contains(bm))
                        inheritedMethodsList.Add(bm);
                }
            }
            inheritBase = inheritBase.BaseType;
        }
        _inheritedMethods = new HashSet<IMethodSymbol>(inheritedMethodsList, SymbolEqualityComparer.Default);
        var methods = directMethods.Concat(inheritedMethodsList).ToArray();

        // Get LayoutPlanner's pre-computed naming for public methods and Udon events
        var typeLayout = _ctx.Planner.GetLayout(_ctx.ClassSymbol);

        // First pass: assign labels, params, return vars (skip generic definitions)
        _ctx.NextMethodIndex = 0;
        foreach (var method in methods)
        {
            // Generic method definitions are not emitted directly;
            // concrete specializations are generated on demand at call sites.
            if (method.IsGenericMethod) continue;

            var idx = _ctx.NextMethodIndex++;
            _ctx.MethodIndices[method] = idx;

            // All methods (including overrides) are in typeLayout.Methods.
            // Override methods already have baseMl assigned by LayoutPlanner.
            var ml = typeLayout.Methods[method];
            var exportName = ml.ExportName;
            var label = _ctx.Module.DefineLabel(exportName);
            _ctx.MethodLabels[method] = label;

            // Pre-define body label for exported methods so internal calls can
            // skip the re-entrance preamble regardless of emit order.
            // Property setters with FieldChangeCallback are also exported (even if private).
            bool hasVarChangeCallback = method.MethodKind == MethodKind.PropertySet
                && method.AssociatedSymbol is IPropertySymbol setProp
                && _ctx.FieldChangeCallbacks.ContainsValue(setProp.Name);
            bool willExport = ((method.MethodKind == MethodKind.Ordinary
                    || method.MethodKind == MethodKind.PropertyGet
                    || method.MethodKind == MethodKind.PropertySet)
                && (method.DeclaredAccessibility == Accessibility.Public
                    || UdonEventNames.ContainsKey(method.Name)))
                || method.MethodKind == MethodKind.ExplicitInterfaceImplementation
                || hasVarChangeCallback;
            if (willExport)
                _ctx.MethodBodyLabels[method] = _ctx.Module.DefineLabel(ml.BodyLabel);

            _ctx.MethodVarPrefix[method] = exportName;

            // Declare params using LayoutPlanner IDs
            var paramVarIds = new string[method.Parameters.Length];
            for (int i = 0; i < method.Parameters.Length; i++)
            {
                var param = method.Parameters[i];
                if (ml.TupleParamIds != null && i < ml.TupleParamIds.Count && ml.TupleParamIds[i] != null)
                {
                    var tupleType = (INamedTypeSymbol)param.Type;
                    var tupleParamIds = new string[ml.TupleParamIds[i].Count];
                    for (int ei = 0; ei < ml.TupleParamIds[i].Count; ei++)
                    {
                        var elemType = GetUdonType(tupleType.TupleElements[ei].Type);
                        _ctx.Vars.DeclareVar(ml.TupleParamIds[i][ei], elemType);
                        tupleParamIds[ei] = ml.TupleParamIds[i][ei];
                    }
                    _ctx.MethodTupleParamVarIds[(method, i)] = tupleParamIds;
                    continue;
                }

                var isDelegateParam = param.Type is INamedTypeSymbol nt && nt.DelegateInvokeMethod != null;
                var udonType = isDelegateParam ? "SystemUInt32" : GetUdonType(param.Type);
                _ctx.Vars.DeclareVar(ml.ParamIds[i], udonType);
                paramVarIds[i] = ml.ParamIds[i];
            }
            _ctx.MethodParamVarIds[method] = paramVarIds;

            // Declare return var(s)
            if (!method.ReturnsVoid)
            {
                if (ml.TupleReturnIds != null)
                {
                    var tupleType = (INamedTypeSymbol)method.ReturnType;
                    var tupleRetIds = new string[ml.TupleReturnIds.Count];
                    for (int i = 0; i < ml.TupleReturnIds.Count; i++)
                    {
                        var elemType = GetUdonType(tupleType.TupleElements[i].Type);
                        _ctx.Vars.DeclareVar(ml.TupleReturnIds[i], elemType);
                        tupleRetIds[i] = ml.TupleReturnIds[i];
                    }
                    _ctx.MethodTupleRetVars[method] = tupleRetIds;
                }
                else if (ml.ReturnId != null)
                {
                    var retType = GetUdonType(method.ReturnType);
                    _ctx.Vars.DeclareVar(ml.ReturnId, retType);
                    _ctx.MethodRetVars[method] = ml.ReturnId;
                    _ctx.MethodRetTypes[method] = retType;
                }
            }

            // Declare convention variables for delegate parameters
            DeclareDelegateConventionVars(method, idx);
        }

        // Collect foreign static methods referenced by this class
        var foreignStatics = CollectForeignStaticMethods(methods);
        foreach (var fm in foreignStatics)
            _ctx.RegisterMethod(fm, SanitizeId(fm.Name));

        // Collect base class instance methods referenced by this class.
        // Exclude methods already in the methods array (inherited methods are already there).
        var methodSet = new HashSet<IMethodSymbol>(methods, SymbolEqualityComparer.Default);
        var baseInstanceMethods = CollectBaseInstanceMethods(methods)
            .Where(bm => !methodSet.Contains(bm))
            .ToArray();
        foreach (var bm in baseInstanceMethods)
            _ctx.RegisterMethod(bm, SanitizeId(bm.Name));

        // Ensure retaddr const exists
        _ctx.Vars.DeclareConst("SystemUInt32", "0xFFFFFFFF");

        // Pre-scan for non-tail self-recursive calls to declare ret addr stack before _start emission
        foreach (var method in methods)
            if (HasNonTailSelfRecursiveCall(method))
            {
                EnsureRetAddrStack();
                break;
            }

        // Second pass: emit bodies (skip generic definitions)
        foreach (var method in methods)
        {
            if (method.IsGenericMethod) continue;
            EmitMethod(method);
        }

        // Emit foreign static method bodies
        foreach (var fm in foreignStatics)
            EmitMethod(fm);

        // Emit base class instance method bodies
        foreach (var bm in baseInstanceMethods)
            EmitMethod(bm);

        // Emit interface bridge exports (when interface and class layouts differ)
        EmitInterfaceBridges();

        // Emit pending local functions and generic specializations (may chain)
        while (_ctx.PendingLocalFunctions.Count > 0 || _ctx.PendingGenericSpecs.Count > 0)
        {
            if (_ctx.PendingLocalFunctions.Count > 0)
            {
                var batch = _ctx.PendingLocalFunctions.ToList();
                _ctx.PendingLocalFunctions.Clear();
                foreach (var (sym, _) in batch)
                    EmitMethod(sym);
            }
            if (_ctx.PendingGenericSpecs.Count > 0)
            {
                var batch = _ctx.PendingGenericSpecs.ToList();
                _ctx.PendingGenericSpecs.Clear();
                foreach (var spec in batch)
                    EmitMethod(spec);
            }
        }

        // Synthesize _start if there are field initializers or ret addr stack but no user-defined Start()
        if ((_ctx.FieldInitOps.Count > 0 || _ctx.FieldChangeCallbacks.Count > 0) && !methods.Any(m => UdonEventNames.TryGetValue(m.Name, out var en) && en == "_start"))
        {
            var label = _ctx.Module.DefineLabel("_start");
            _ctx.Module.AddExport("_start", label);
            _ctx.Module.MarkLabel(label);
            var sentinel = _ctx.Vars.DeclareConst("SystemUInt32", "0xFFFFFFFF");
            _ctx.Module.AddPush(sentinel);
            // Body label separates sentinel push from method body (matches EmitMethod pattern).
            // Without this, the sentinel PUSH bleeds into the first COPY's push count.
            var startBodyLabel = _ctx.Module.DefineLabel("_start__body");
            _ctx.Module.AddLabel(startBodyLabel);
            _ctx.Module.MarkLabel(startBodyLabel);
            EmitFieldInitializers();
            _ctx.Module.AddReturn("__intnl_returnJump_SystemUInt32_0");
        }
    }

    void EmitInterfaceBridges()
    {
        var bridges = _ctx.Planner.ComputeBridges(_ctx.ClassSymbol);
        foreach (var (ifaceMethod, ifaceMl, classMl) in bridges)
        {
            if (ifaceMethod.Parameters.Any(p => p.Type.IsTupleType))
                throw new System.NotSupportedException(
                    $"Tuple parameters on interface method '{ifaceMethod.ContainingType.Name}.{ifaceMethod.Name}' are not supported in interface bridges.");
            if (ifaceMethod.ReturnType.IsTupleType)
                throw new System.NotSupportedException(
                    $"Tuple return from interface method '{ifaceMethod.ContainingType.Name}.{ifaceMethod.Name}' is not supported in interface bridges.");
            // Declare interface param/return variables (idempotent — may already exist
            // if another class method uses the same counter-based name)
            for (int i = 0; i < ifaceMethod.Parameters.Length; i++)
            {
                if (ifaceMl.ParamIds[i] != classMl.ParamIds[i])
                {
                    var udonType = GetUdonType(ifaceMethod.Parameters[i].Type);
                    _ctx.Vars.TryDeclareVar(ifaceMl.ParamIds[i], udonType);
                }
            }
            if (ifaceMl.ReturnId != null && ifaceMl.ReturnId != classMl.ReturnId)
            {
                var retType = GetUdonType(ifaceMethod.ReturnType);
                _ctx.Vars.TryDeclareVar(ifaceMl.ReturnId, retType);
            }

            // Export the interface name → bridge trampoline
            var bridgeLabel = _ctx.Module.DefineLabel(ifaceMl.ExportName);
            _ctx.Module.AddExport(ifaceMl.ExportName, bridgeLabel);
            _ctx.Module.MarkLabel(bridgeLabel);

            var sentinel = _ctx.Vars.DeclareConst("SystemUInt32", "0xFFFFFFFF");

            // Copy interface params → class params (only if names differ)
            for (int i = 0; i < ifaceMethod.Parameters.Length; i++)
            {
                if (ifaceMl.ParamIds[i] != classMl.ParamIds[i])
                    _ctx.Module.AddCopy(ifaceMl.ParamIds[i], classMl.ParamIds[i]);
            }

            // Call class body via returnJump so control returns here after body executes
            if (_ctx.MethodBodyLabels.TryGetValue(
                    _ctx.ClassSymbol.FindImplementationForInterfaceMember(ifaceMethod) as IMethodSymbol,
                    out var bodyLabel))
            {
                bool needsReturnCopy = ifaceMl.ReturnId != null && classMl.ReturnId != null
                    && ifaceMl.ReturnId != classMl.ReturnId;

                if (needsReturnCopy)
                {
                    // Stack-based protocol: push sentinel (for bridge's own return),
                    // then push continuation label (for body method's return)
                    _ctx.Module.AddPush(sentinel);
                    var bridgeContinuation = _ctx.Module.DefineLabel($"__bridge_continue_{ifaceMl.ExportName}");
                    _ctx.Module.AddPushLabel(bridgeContinuation);
                    _ctx.Module.AddJump(bodyLabel);
                    _ctx.Module.MarkLabel(bridgeContinuation);

                    // Copy class return → interface return
                    _ctx.Module.AddCopy(classMl.ReturnId, ifaceMl.ReturnId);

                    // Return (consumes sentinel from stack → halts)
                    _ctx.Module.AddReturn("__intnl_returnJump_SystemUInt32_0");
                }
                else
                {
                    // No return copy needed — push sentinel and jump to body directly.
                    // Body's RET consumes sentinel from stack → halts.
                    _ctx.Module.AddPush(sentinel);
                    _ctx.Module.AddJump(bodyLabel);
                }
            }
            else
            {
                throw new System.InvalidOperationException(
                    $"Interface bridge for '{ifaceMl.ExportName}': "
                  + $"no body label found for implementation of '{ifaceMethod.Name}'.");
            }
        }
    }

    // Explicit interface implementations produce names with dots
    // (e.g. "Namespace.IFoo.get_Bar") which are invalid in UASM identifiers.
    static string SanitizeId(string name) => name.Replace('.', '_');

    void DeclareDelegateConventionVars(IMethodSymbol method, int idx)
    {
        foreach (var param in method.Parameters)
        {
            if (param.Type is not INamedTypeSymbol namedType || namedType.DelegateInvokeMethod == null)
                continue;

            var invoke = namedType.DelegateInvokeMethod;
            var argVarIds = new string[invoke.Parameters.Length];
            for (int j = 0; j < invoke.Parameters.Length; j++)
            {
                var argType = GetUdonType(invoke.Parameters[j].Type);
                argVarIds[j] = _ctx.Vars.DeclareVar($"__dlg_{idx}_{param.Name}_a{j}", argType);
            }
            string retVarId = null;
            if (!invoke.ReturnsVoid)
            {
                var retType = GetUdonType(invoke.ReturnType);
                retVarId = _ctx.Vars.DeclareVar($"__dlg_{idx}_{param.Name}_ret", retType);
            }
            _ctx.DelegateParamConventions[(idx, param.Ordinal)] = new DelegateConvention
            {
                ArgVarIds = argVarIds, RetVarId = retVarId
            };
        }
    }

    void EmitMethod(IMethodSymbol method)
    {
        _ctx.CurrentMethod = method;
        var label = _ctx.MethodLabels[method];
        var exportName = _ctx.MethodVarPrefix[method]; // stored from first pass (matches label name)
        var idx = _ctx.MethodIndices[method];

        // Generic specializations are internal-only (never exported)
        bool isGenericSpec = method.IsGenericMethod && !method.IsDefinition;

        // FieldChangeCallback: check if this setter has an associated callback field
        string fcbFieldName = null;
        if (method.MethodKind == MethodKind.PropertySet
            && method.AssociatedSymbol is IPropertySymbol setterProp)
        {
            foreach (var kvp in _ctx.FieldChangeCallbacks)
                if (kvp.Value == setterProp.Name) { fcbFieldName = kvp.Key; break; }
        }

        bool isOwnOrInherited = SymbolEqualityComparer.Default.Equals(method.ContainingType, _ctx.ClassSymbol)
            || _inheritedMethods.Contains(method);
        bool shouldExport = !isGenericSpec
            && isOwnOrInherited
            && (method.MethodKind == MethodKind.Ordinary
                || method.MethodKind == MethodKind.PropertyGet
                || method.MethodKind == MethodKind.PropertySet)
            && (method.DeclaredAccessibility == Accessibility.Public
                || UdonEventNames.ContainsKey(method.Name)
                || fcbFieldName != null);
        if (shouldExport)
        {
            // FieldChangeCallback preamble: emit _onVarChange_ export before setter export
            if (fcbFieldName != null)
            {
                var varChangeExportName = $"_onVarChange_{fcbFieldName}";
                var varChangeLabel = _ctx.Module.DefineLabel(varChangeExportName);
                _ctx.Module.AddExport(varChangeExportName, varChangeLabel);
                _ctx.Module.MarkLabel(varChangeLabel);

                // Preamble: swap new/old values
                // 1. field → value param (new value to setter parameter)
                var paramId = _ctx.MethodParamVarIds[method][0];
                _ctx.Module.AddCopy(fcbFieldName, paramId);
                // 2. _old_ → field (restore field to old value)
                _ctx.Module.AddCopy($"__old_{fcbFieldName}", fcbFieldName);
                // Fall through to setter body
            }

            _ctx.Module.AddExport(exportName, label);
            _ctx.Module.MarkLabel(label);

            // Stack-based sentinel: push 0xFFFFFFFF onto VM stack so RET (PUSH+COPY+JUMP_INDIRECT)
            // consumes it and halts cleanly when called externally (matches UdonSharp protocol).
            var sentinel = _ctx.Vars.DeclareConst("SystemUInt32", "0xFFFFFFFF");
            _ctx.Module.AddPush(sentinel);

            // Body label (pre-defined in first pass): internal JUMP calls skip the preamble
            var bodyLabel = _ctx.MethodBodyLabels[method];
            _ctx.Module.AddLabel(bodyLabel);
            _ctx.Module.MarkLabel(bodyLabel);
        }
        else if (_ctx.MethodBodyLabels.TryGetValue(method, out var bodyLbl))
        {
            // Explicit interface impl: only mark body label (bridge handles export)
            _ctx.Module.AddLabel(bodyLbl);
            _ctx.Module.MarkLabel(bodyLbl);
        }
        else
        {
            _ctx.Module.AddLabel(label);
            _ctx.Module.MarkLabel(label);
        }

        // Scope for method locals
        _ctx.Vars.PushScope();

        // Emit field initializers at the start of _start
        if (exportName == "_start")
            EmitFieldInitializers();

        // Set up type param map for generic specializations
        if (isGenericSpec)
        {
            var orig = method.OriginalDefinition;
            var map = new Dictionary<ITypeParameterSymbol, ITypeSymbol>(SymbolEqualityComparer.Default);
            for (int i = 0; i < orig.TypeParameters.Length; i++)
                map[orig.TypeParameters[i]] = method.TypeArguments[i];
            _ctx.TypeParamMap = map;
        }

        // Get method body IOperation (from OriginalDefinition for generic specializations)
        var bodySource = isGenericSpec ? method.OriginalDefinition : method;
        var syntaxRef = bodySource.DeclaringSyntaxReferences.FirstOrDefault();
        if (syntaxRef != null)
        {
            var syntax = syntaxRef.GetSyntax();
            var tree = syntax.SyntaxTree;
            var model = _ctx.Compilation.GetSemanticModel(tree);

            var bodyOp = model.GetOperation(syntax);
            _ctx.GotoLabels.Clear();
            PreScanGotoLabels(bodyOp);
            if (bodyOp is IMethodBodyOperation methodBody)
            {
                if (methodBody.BlockBody != null)
                    VisitOperation(methodBody.BlockBody);
                else if (methodBody.ExpressionBody != null)
                    VisitOperation(methodBody.ExpressionBody);
            }
            else if (bodyOp is ILocalFunctionOperation localFuncOp)
            {
                if (localFuncOp.Body != null)
                    VisitOperation(localFuncOp.Body);
            }
            else if (bodyOp is IAnonymousFunctionOperation anonFunc)
            {
                if (anonFunc.Body is IBlockOperation anonBlock)
                    VisitOperation(anonBlock);
                else if (anonFunc.Body != null && _ctx.MethodRetVars.TryGetValue(method, out var lambdaRetId))
                {
                    var resultId = VisitExpression(anonFunc.Body);
                    _ctx.Module.AddCopy(resultId, lambdaRetId);
                }
            }
            else if (bodyOp is IBlockOperation block)
                VisitOperation(block);
            // Expression-bodied property: int X => expr;
            else if (syntax is PropertyDeclarationSyntax propDecl
                     && propDecl.ExpressionBody != null)
            {
                var exprOp = model.GetOperation(propDecl.ExpressionBody.Expression);
                if (exprOp != null && _ctx.MethodRetVars.TryGetValue(method, out var retId))
                {
                    var resultId = VisitExpression(exprOp);
                    _ctx.Module.AddCopy(resultId, retId);
                }
            }
            // Block-bodied property accessor: int X { get { return expr; } }
            else if (syntax is AccessorDeclarationSyntax accessorDecl)
            {
                var accessorOp = model.GetOperation(accessorDecl);
                if (accessorOp is IMethodBodyOperation accessorBody)
                {
                    if (accessorBody.BlockBody != null)
                        VisitOperation(accessorBody.BlockBody);
                    else if (accessorBody.ExpressionBody != null)
                        VisitOperation(accessorBody.ExpressionBody);
                }
                else if (accessorOp is IBlockOperation accessorBlock)
                    VisitOperation(accessorBlock);
            }
        }

        _ctx.Vars.PopScope();

        // FieldChangeCallback epilogue: update _old_ to current value
        if (fcbFieldName != null)
            _ctx.Module.AddCopy(fcbFieldName, $"__old_{fcbFieldName}");

        // Clear type param map after generic specialization emission
        if (isGenericSpec)
            _ctx.TypeParamMap = null;

        // Method epilogue: return
        _ctx.Module.AddReturn("__intnl_returnJump_SystemUInt32_0");
        _ctx.CurrentMethod = null;
    }

    void EmitFieldInitializers()
    {
        foreach (var (fieldId, initOp, fieldType) in _ctx.FieldInitOps)
        {
            try
            {
                // Bare array initializer { 1, 2, 3 } → synthesize array creation + element Set
                if (initOp is IArrayInitializerOperation arrayInit)
                {
                    var arrTypeSym = (IArrayTypeSymbol)fieldType;
                    var arrayType = GetUdonType(arrTypeSym);
                    var elementType = GetArrayElemType(arrTypeSym);
                    var sizeConst = _ctx.Vars.DeclareConst("SystemInt32", arrayInit.ElementValues.Length.ToString());
                    _ctx.Module.AddPush(sizeConst);
                    _ctx.Module.AddPush(fieldId);
                    AddExternChecked($"{arrayType}.__ctor__SystemInt32__{arrayType}");
                    for (int i = 0; i < arrayInit.ElementValues.Length; i++)
                    {
                        var valId = VisitExpression(arrayInit.ElementValues[i]);
                        var idxConst = _ctx.Vars.DeclareConst("SystemInt32", i.ToString());
                        _ctx.Module.AddPush(fieldId);
                        _ctx.Module.AddPush(idxConst);
                        _ctx.Module.AddPush(valId);
                        AddExternChecked($"{arrayType}.__Set__SystemInt32_{elementType}__SystemVoid");
                    }
                    continue;
                }

                var valueId = VisitExpression(initOp);

                // Udon COPY overwrites destination type tag with source type.
                // When initOp type differs from field type (e.g. int literal 0 → float field),
                // emit numeric conversion instead of raw COPY to prevent type-tag corruption.
                if (initOp.Type != null && fieldType != null
                    && !SymbolEqualityComparer.Default.Equals(initOp.Type, fieldType)
                    && ExternResolver.IsNumericType(initOp.Type)
                    && ExternResolver.IsNumericType(fieldType))
                {
                    var methodName = ExternResolver.GetConvertMethodName(fieldType);
                    if (methodName != null)
                    {
                        var srcType = GetUdonType(initOp.Type);
                        var dstType = GetUdonType(fieldType);
                        var convertedId = _ctx.Vars.DeclareTemp(dstType);
                        _ctx.Module.AddPush(valueId);
                        _ctx.Module.AddPush(convertedId);
                        AddExternChecked($"SystemConvert.__{methodName}__{srcType}__{dstType}");
                        _ctx.Module.AddCopy(convertedId, fieldId);
                        continue;
                    }
                }

                _ctx.Module.AddCopy(valueId, fieldId);
            }
            catch (System.NotSupportedException ex)
            {
                var loc = initOp.Syntax?.GetLocation()?.GetLineSpan();
                _ctx.Diagnostics.Add(new EmitDiagnostic
                {
                    Severity = "Warning",
                    Message = $"Field '{fieldId}' initializer not supported, will be default(T) at runtime: {ex.Message}",
                    FilePath = loc?.Path ?? "",
                    Line = (loc?.StartLinePosition.Line ?? -1) + 1,
                    Character = (loc?.StartLinePosition.Character ?? -1) + 1,
                });
            }
        }

        // Initialize _old_ variables for FieldChangeCallback fields
        foreach (var kvp in _ctx.FieldChangeCallbacks)
            _ctx.Module.AddCopy(kvp.Key, $"__old_{kvp.Key}");
    }

    // ── IOperation visitor (facade — delegates to handlers) ──

    void VisitOperation(IOperation op)
    {
        foreach (var h in _stmtHandlers)
            if (h.CanHandle(op)) { h.Handle(op); return; }
        throw new System.NotSupportedException($"Unsupported operation: {op.Kind} ({op.GetType().Name})");
    }

    void PreScanGotoLabels(IOperation op)
    {
        if (op == null) return;
        if (op is ILabeledOperation labeled)
        {
            var label = _ctx.Module.DefineLabel($"__goto_{labeled.Label.Name}");
            _ctx.GotoLabels[labeled.Label] = label;
        }
        foreach (var child in op.Children)
            PreScanGotoLabels(child);
    }

    // ── Expression visitor (facade — delegates to handlers) ──

    string VisitExpression(IOperation op)
    {
        if (op == null)
            throw new System.NotSupportedException("VisitExpression called with null operation");
        foreach (var h in _exprHandlers)
            if (h.CanHandle(op)) return h.Handle(op);
        throw new System.NotSupportedException(
            $"Unsupported expression: {op.Kind} ({op.GetType().Name})");
    }

    void EnsureRetAddrStack()
    {
        // Disabled: recursion and re-entrance stack not supported (matches UdonSharp behavior)
    }

    bool HasNonTailSelfRecursiveCall(IMethodSymbol method)
    {
        var syntaxRef = method.DeclaringSyntaxReferences.FirstOrDefault();
        if (syntaxRef == null) return false;
        var syntax = syntaxRef.GetSyntax();
        var model = _ctx.Compilation.GetSemanticModel(syntax.SyntaxTree);
        var bodyOp = model.GetOperation(syntax);
        return ContainsNonTailSelfCall(bodyOp, method);
    }

    static bool ContainsNonTailSelfCall(IOperation op, IMethodSymbol method)
    {
        if (op == null) return false;

        // return self(args) → tail call; only check args for non-tail self-calls
        if (op is IReturnOperation ret && ret.ReturnedValue is IInvocationOperation retInv
            && SymbolEqualityComparer.Default.Equals(retInv.TargetMethod, method))
        {
            foreach (var arg in retInv.Arguments)
                if (ContainsNonTailSelfCall(arg, method))
                    return true;
            return false;
        }

        if (op is IInvocationOperation inv
            && SymbolEqualityComparer.Default.Equals(inv.TargetMethod, method))
            return true;
        foreach (var child in op.Children)
            if (ContainsNonTailSelfCall(child, method))
                return true;
        return false;
    }

    IMethodSymbol[] CollectForeignStaticMethods(IMethodSymbol[] classMethods)
    {
        var result = new HashSet<IMethodSymbol>(SymbolEqualityComparer.Default);
        // Seed: walk class method bodies
        foreach (var method in classMethods)
        {
            var syntaxRef = method.DeclaringSyntaxReferences.FirstOrDefault();
            if (syntaxRef == null) continue;
            var syntax = syntaxRef.GetSyntax();
            var model = _ctx.Compilation.GetSemanticModel(syntax.SyntaxTree);
            var bodyOp = model.GetOperation(syntax);
            CollectForeignStaticCallsInOperation(bodyOp, result);
        }
        // Recursively walk foreign static bodies to find transitive dependencies
        var visited = new HashSet<IMethodSymbol>(result, SymbolEqualityComparer.Default);
        var queue = new Queue<IMethodSymbol>(result);
        while (queue.Count > 0)
        {
            var fm = queue.Dequeue();
            var syntaxRef = fm.DeclaringSyntaxReferences.FirstOrDefault();
            if (syntaxRef == null) continue;
            var syntax = syntaxRef.GetSyntax();
            var model = _ctx.Compilation.GetSemanticModel(syntax.SyntaxTree);
            var bodyOp = model.GetOperation(syntax);
            var before = result.Count;
            CollectForeignStaticCallsInOperation(bodyOp, result);
            foreach (var newMethod in result.Except(visited))
            {
                visited.Add(newMethod);
                queue.Enqueue(newMethod);
            }
        }
        return result.ToArray();
    }

    void CollectForeignStaticCallsInOperation(IOperation op, HashSet<IMethodSymbol> result)
    {
        if (op == null) return;
        if (op is IInvocationOperation inv && _ctx.IsForeignStatic(inv.TargetMethod))
        {
            var original = inv.TargetMethod.ReducedFrom ?? inv.TargetMethod;
            // Skip generic method definitions — they are monomorphized on demand at call sites
            if (!original.IsGenericMethod)
                result.Add(original);
        }
        foreach (var child in op.Children)
            CollectForeignStaticCallsInOperation(child, result);
    }


    IMethodSymbol[] CollectBaseInstanceMethods(IMethodSymbol[] classMethods)
    {
        var result = new HashSet<IMethodSymbol>(SymbolEqualityComparer.Default);
        foreach (var method in classMethods)
        {
            var syntaxRef = method.DeclaringSyntaxReferences.FirstOrDefault();
            if (syntaxRef == null) continue;
            var syntax = syntaxRef.GetSyntax();
            var model = _ctx.Compilation.GetSemanticModel(syntax.SyntaxTree);
            var bodyOp = model.GetOperation(syntax);
            CollectBaseInstanceCallsInOperation(bodyOp, result);
        }
        return result.ToArray();
    }

    void CollectBaseInstanceCallsInOperation(IOperation op, HashSet<IMethodSymbol> result)
    {
        if (op == null) return;
        if (op is IInvocationOperation inv && _ctx.IsBaseInstanceMethod(inv.TargetMethod))
            result.Add(inv.TargetMethod);
        foreach (var child in op.Children)
            CollectBaseInstanceCallsInOperation(child, result);
    }


    // Format a compile-time constant value for the UASM data section.
    // Returns null if the value cannot be represented as a data section default.
    static string FormatConstForDataSection(string udonType, object value, ITypeSymbol fieldType)
    {
        // For enum fields, use the underlying integer value
        if (fieldType.TypeKind == TypeKind.Enum && value is System.IConvertible ic)
            return ic.ToString(System.Globalization.CultureInfo.InvariantCulture);
        return udonType switch
        {
            "SystemInt32" or "SystemInt64" or "SystemByte" or "SystemSByte"
                or "SystemInt16" or "SystemUInt16" or "SystemUInt32" or "SystemUInt64"
                => value.ToString(),
            "SystemSingle" => ((System.IConvertible)value).ToSingle(System.Globalization.CultureInfo.InvariantCulture)
                .ToString(System.Globalization.CultureInfo.InvariantCulture),
            "SystemDouble" => ((System.IConvertible)value).ToDouble(System.Globalization.CultureInfo.InvariantCulture)
                .ToString(System.Globalization.CultureInfo.InvariantCulture),
            "SystemBoolean" => (bool)value ? "True" : "False",
            "SystemString" => value.ToString(),
            "SystemChar" => value.ToString(),
            _ => null,
        };
    }

    /// <summary>
    /// コンパイル時に評価可能な非定数フィールド初期化子を CLR オブジェクトとして生成する。
    /// 成功時は CLR オブジェクト（例: int[5]）を返し、評価不可の場合は null を返す。
    /// </summary>
    object TryEvaluateFieldInitForHeap(IOperation initOp, ITypeSymbol fieldType)
    {
        if (initOp is IArrayCreationOperation arrayCreation)
            return TryEvalArrayCreation(arrayCreation);

        if (initOp is IArrayInitializerOperation arrayInit && fieldType is IArrayTypeSymbol arrType)
            return TryEvalArrayInitializer(arrayInit, arrType);

        return null;
    }

    object TryEvalArrayCreation(IArrayCreationOperation op)
    {
        if (op.DimensionSizes.Length != 1) return null;

        var arrTypeSym = op.Type as IArrayTypeSymbol;
        if (arrTypeSym == null) return null;

        var elemClrType = ResolveClrTypeForConst(arrTypeSym.ElementType);
        if (elemClrType == null) return null;

        int size;
        if (op.DimensionSizes[0].ConstantValue.HasValue
            && op.DimensionSizes[0].ConstantValue.Value is int constSize)
        {
            size = constSize;
        }
        else if (op.Initializer != null)
        {
            size = op.Initializer.ElementValues.Length;
        }
        else
        {
            return null;
        }

        var array = Array.CreateInstance(elemClrType, size);

        if (op.Initializer != null)
        {
            if (!TryPopulateArray(array, op.Initializer, elemClrType))
                return null;
        }

        return array;
    }

    object TryEvalArrayInitializer(IArrayInitializerOperation init, IArrayTypeSymbol arrType)
    {
        var elemClrType = ResolveClrTypeForConst(arrType.ElementType);
        if (elemClrType == null) return null;

        var array = Array.CreateInstance(elemClrType, init.ElementValues.Length);
        if (!TryPopulateArray(array, init, elemClrType))
            return null;

        return array;
    }

    static Type ResolveClrTypeForConst(ITypeSymbol type)
    {
        return type.SpecialType switch
        {
            SpecialType.System_Boolean => typeof(bool),
            SpecialType.System_Byte => typeof(byte),
            SpecialType.System_SByte => typeof(sbyte),
            SpecialType.System_Int16 => typeof(short),
            SpecialType.System_UInt16 => typeof(ushort),
            SpecialType.System_Int32 => typeof(int),
            SpecialType.System_UInt32 => typeof(uint),
            SpecialType.System_Int64 => typeof(long),
            SpecialType.System_UInt64 => typeof(ulong),
            SpecialType.System_Single => typeof(float),
            SpecialType.System_Double => typeof(double),
            SpecialType.System_String => typeof(string),
            SpecialType.System_Char => typeof(char),
            _ => null,
        };
    }

    static bool TryPopulateArray(Array array, IArrayInitializerOperation init, Type elemClrType)
    {
        for (int i = 0; i < init.ElementValues.Length; i++)
        {
            var elemOp = init.ElementValues[i];
            if (!elemOp.ConstantValue.HasValue)
                return false;
            var val = elemOp.ConstantValue.Value;
            if (val == null)
                continue;
            try
            {
                array.SetValue(Convert.ChangeType(val, elemClrType), i);
            }
            catch
            {
                return false;
            }
        }
        return true;
    }


    void FlushVariablesToModule()
    {
        foreach (var entry in _ctx.Vars.GetAllEntries())
            _ctx.Module.DeclareVariable(entry.Id, entry.UdonType, entry.DefaultValue, entry.Flags, entry.SyncMode, entry.ConstValue);
    }

    void SyncOptimizerConsts()
    {
        var constValues = _ctx.Module.GetConstValues();
        var varTypes = _ctx.Module.GetVariableTypes();
        foreach (var kv in constValues)
        {
            if (!varTypes.TryGetValue(kv.Key, out var type)) continue;
            _ctx.Vars.TryDeclareVar(kv.Key, type);
            _ctx.Vars.SetConstValue(kv.Key, kv.Value);
        }
    }
}
