using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;
using UdonSharp;
using VRC.Udon.Editor;

/// <summary>
/// Facade: entry point for USugar compiler (menu items, toggle, static init).
/// Delegates to USugarHarmonyPatcher, USugarCompilationOrchestrator, etc.
/// </summary>
[InitializeOnLoad]
public static class USugarCompiler
{
    const string OverrideMenuPath = "USugar/Override Compiler";
    const string OverridePrefKey = "USugar_OverrideUdonSharp";

    internal static bool OverrideEnabled
    {
        get => EditorPrefs.GetBool(OverridePrefKey, false);
        set => EditorPrefs.SetBool(OverridePrefKey, value);
    }

    static USugarCompiler()
    {
        try
        {
            USugarHarmonyPatcher.Initialize();
        }
        catch (Exception ex)
        {
            USugarLog.Error($"Static init failed: {ex}");
        }
    }

    [MenuItem(OverrideMenuPath)]
    static void ToggleOverride()
    {
        var next = !OverrideEnabled;
        OverrideEnabled = next;
        if (next) 
            USugarHarmonyPatcher.ApplyPatches();
        else 
            USugarHarmonyPatcher.RemovePatches();
    }

    [MenuItem(OverrideMenuPath, true)]
    static bool ToggleOverrideValidate()
    {
        Menu.SetChecked(OverrideMenuPath, OverrideEnabled);
        return true;
    }
    [MenuItem("USugar/Compile/USugar")]
    public static void CompileAndApply() => USugarCompilationOrchestrator.CompileInternal(applyToAssets: true, force: true, dumpEnabled: DumpIREnabled);

    static bool DumpIREnabled
    {
        get => UnityEditor.EditorPrefs.GetBool("USugar_DumpIR", false);
        set => UnityEditor.EditorPrefs.SetBool("USugar_DumpIR", value);
    }

    const string DumpIRMenuPath = "USugar/Dump IR";

    [MenuItem(DumpIRMenuPath)]
    static void ToggleDumpIR() => DumpIREnabled = !DumpIREnabled;

    [MenuItem(DumpIRMenuPath, true)]
    static bool ToggleDumpIRValidate()
    {
        Menu.SetChecked(DumpIRMenuPath, DumpIREnabled);
        return true;
    }

    [MenuItem("USugar/Compile/UdonSharp")]
    static void ExportReferenceUasm()
    {
        var wasEnabled = OverrideEnabled;
        OverrideEnabled = false;
        // Remove all Harmony patches to ensure UdonSharp runs completely unmodified
        USugarHarmonyPatcher.RemovePatches();
        try
        {
            var compileSync = USugarReflectionTargets.CompileSyncMethod;
            if (compileSync == null)
            {
                USugarLog.Error("CompileSync not found");
                return;
            }
            var options = USugarReflectionTargets.CompileOptionsType != null
                ? Activator.CreateInstance(USugarReflectionTargets.CompileOptionsType) : null;
            compileSync.Invoke(null, new[] { options });

            var refDir = "Library/USugarCache/Reference";
            Directory.CreateDirectory(refDir);

            var instance = USugarReflectionTargets.GetEditorCacheInstance();
            if (instance == null)
            {
                USugarLog.Info("UdonSharpEditorCache instance not available — skipping reference export");
                return;
            }

            var programAssets = Resources.FindObjectsOfTypeAll<UdonSharpProgramAsset>();
            int saved = 0, stale = 0;
            foreach (var asset in programAssets)
            {
                if (asset.sourceCsScript == null) continue;
                var uasm = USugarReflectionTargets.GetUasmStr?.Invoke(instance, new object[] { asset }) as string;
                if (string.IsNullOrEmpty(uasm)) continue;
                // The editor cache still holds USugar's own output when the stock compile failed for this
                // asset (e.g. it uses USugar-only features) — exporting that as "reference" would silently
                // diff USugar against itself.
                if (uasm.StartsWith("# Generated by USugar"))
                {
                    stale++;
                    continue;
                }
                var name = asset.sourceCsScript.name;
                File.WriteAllText(Path.Combine(refDir, $"{name}.uasm"), uasm);
                saved++;
            }

            if (stale > 0)
                USugarLog.Warn($"{stale} asset(s) still carry USugar output in the editor cache — the stock compile did not produce them (likely failed; check the console). They were NOT exported as reference.");
            USugarLog.Info($"Exported {saved} reference UASM files to {refDir}");
        }
        catch (Exception ex)
        {
            USugarLog.Error($"Reference export failed: {ex}");
        }
        finally
        {
            OverrideEnabled = wasEnabled;
            if (wasEnabled)
            {
                USugarHarmonyPatcher.ApplyPatches();
                USugarCompilationOrchestrator.CompileInternal(applyToAssets: true, force: true);
            }
        }
    }

    // Debug utility: uncomment [MenuItem] to dump all registered Udon externs to a text file.
    // Useful for checking if a specific extern signature exists in the current SDK version.
    //[MenuItem("USugar/Dump Udon Extern Registry")]
    public static void DumpExternRegistry()
    {
        var defs = UdonEditorManager.Instance.GetNodeDefinitions()
            .Select(d => d.fullName)
            .Where(n => !string.IsNullOrEmpty(n))
            .OrderBy(n => n)
            .ToArray();

        var outputPath = "Library/USugarCache/udon_extern_registry.txt";
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath));
        File.WriteAllLines(outputPath, defs);
        USugarLog.Info($"Dumped {defs.Length} node definitions → {outputPath}");
    }

    // Regenerates the tracked Event_* snapshot exclusively from the public SDK editor registry.
    // EventRegistryCensusTests validates LayoutPlanner's event tables bidirectionally against it.

    public static void DumpEventRegistry()
    {
        var header = new[]
        {
            "# Udon event node registry census: one row per SDK Event_* node definition, sorted by node name",
            "# (ordinal). Event_Custom* and Event_OnVariableChange are excluded — they are not method-name-bound",
            "# UdonSharpBehaviour events (custom events are user-named; OnVariableChange binds via FieldChangeCallback).",
            "# Format: Event_Name|outParam:TypeFullName,... — RAW registry truth. Export names (_lowerFirst) and",
            "# param heap-var names ({lowerEvent}{UpperParam}) are DERIVED from these rows exactly like stock",
            "# UdonSharp's CompilerUdonInterface.CacheInit; EventRegistryCensusTests pins LayoutPlanner's tables",
            "# bidirectionally against this file.",
            "# Source: UdonEditorManager.Instance.GetNodeDefinitions() — regenerate via USugarCompiler.DumpEventRegistry.",
        };
        var rows = UdonEditorManager.Instance.GetNodeDefinitions()
            .Where(d => !string.IsNullOrEmpty(d.fullName)
                        && d.fullName.StartsWith("Event_", StringComparison.Ordinal)
                        && !d.fullName.StartsWith("Event_Custom", StringComparison.Ordinal)
                        && d.fullName != "Event_OnVariableChange")
            .OrderBy(d => d.fullName, StringComparer.Ordinal)
            .Select(d => d.Outputs.Count == 0
                ? d.fullName
                : d.fullName + "|" + string.Join(",", d.Outputs.Select(p => $"{p.name}:{p.type.FullName}")))
            .ToArray();

        var outputPath = "Assets/USugar/Editor~/Tests/Fixtures/udon_event_registry.txt";
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath));
        File.WriteAllLines(outputPath, header.Concat(rows));
        USugarLog.Info($"Dumped {rows.Length} event node definitions → {outputPath}");
    }
}
