using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

[Flags]
public enum VarFlags
{
    None   = 0,
    Export = 1 << 0,
    Sync   = 1 << 1,
}

/// <summary>
/// Result of UASM code generation from an IrModule.
/// Contains the UASM text, heap sizing info, and constant entries for ApplyConstantValues.
/// </summary>
public struct CodeGenResult
{
    public string Uasm;
    public uint HeapSize;
    public List<(string Id, string UdonType, object Value)> Constants;
}

/// <summary>
/// Generates UASM assembly text from an IrModule.
/// Uses a two-pass approach:
///   Pass 1: Collect instructions into intermediate representation, compute label addresses.
///   Pass 2: Render UASM text with resolved numeric addresses for JUMP/JUMP_IF_FALSE.
/// </summary>
public sealed class CodeGen
{
    // ── Intermediate code representation ──

    enum CodeKind
    {
        Push,           // 8 bytes — operand = var name
        Copy,           // 4 bytes
        Jump,           // 8 bytes — operand = target label name
        JumpIfFalse,    // 8 bytes — operand = target label name
        JumpIndirect,   // 8 bytes — operand = var name
        Extern,         // 8 bytes — operand = extern signature
        Label,          // 0 bytes — labelName = label being defined
        Export,         // 0 bytes — labelName = export name
    }

    struct CodeLine
    {
        public CodeKind Kind;
        public string Operand;     // var name, extern sig, or target label name (Jump/JIF)
        public string LabelName;   // label being defined (Label) or export name (Export)
    }

    static uint GetSize(CodeKind kind) => kind switch
    {
        CodeKind.Push => 8,
        CodeKind.Copy => 4,
        CodeKind.Jump => 8,
        CodeKind.JumpIfFalse => 8,
        CodeKind.JumpIndirect => 8,
        CodeKind.Extern => 8,
        _ => 0, // Label, Export
    };

    // ── State ──

    readonly IrModule _module;
    readonly List<VarDecl> _vars = new();
    readonly HashSet<string> _declaredVarIds = new();
    readonly HashSet<string> _externs = new();
    readonly Dictionary<string, string> _constPool = new();     // "type_value" → varId
    readonly Dictionary<IrBlock, string> _blockLabels = new();

    // Two-pass infrastructure
    readonly List<CodeLine> _code = new();
    readonly Dictionary<string, uint> _labelAddrs = new();
    readonly List<(string VarName, string LabelName)> _retaddrConsts = new();
    readonly List<(string VarName, string LabelName)> _funcRefConsts = new();
    readonly Dictionary<string, string> _funcRefVars = new();

    int _constIdx;
    int _retaddrIdx;
    int _dlgTempIdx;
    int _funcRefIdx;

    // VReg → UASM variable ID
    readonly Dictionary<int, string> _vregVars = new();

    struct VarDecl
    {
        public string Id, UdonType, DefaultValue;
        public VarFlags Flags;
        public string SyncMode;
        public object ConstValue;
    }

    CodeGen(IrModule module) => _module = module;

    /// <summary>Generate UASM from an IrModule with resolved numeric addresses.</summary>
    public static CodeGenResult Generate(IrModule module)
    {
        var gen = new CodeGen(module);
        return gen.Run();
    }

    CodeGenResult Run()
    {
        // Phase 1: Emit reflection variables
        EmitReflectionVars();

        // Phase 2: Emit field declarations
        foreach (var field in _module.Fields)
            DeclareField(field);

        // Phase 3: Assign labels to all blocks and allocate VReg vars
        foreach (var func in _module.Functions)
            PrepareFunction(func);

        // Phase 4: Collect code entries (intermediate representation)
        foreach (var func in _module.Functions)
            EmitFunction(func);

        // Phase 5: Compute label addresses
        ComputeAddresses();

        // Phase 6: Resolve retaddr constants via ApplyConstantValues (not UASM data section).
        // The Udon assembler does not parse hex literals in data section defaults.
        foreach (var (varName, labelName) in _retaddrConsts)
        {
            var addr = _labelAddrs[labelName];
            DeclareVar(varName, "SystemUInt32", null, VarFlags.None, constValue: addr);
        }

        // Phase 6b: Resolve funcref constants (function entry addresses)
        foreach (var (varName, labelName) in _funcRefConsts)
        {
            var addr = _labelAddrs[labelName];
            DeclareVar(varName, "SystemUInt32", null, VarFlags.None, constValue: addr);
        }

        // Phase 7: Build output
        var sb = new StringBuilder();
        sb.Append("# Generated by USugar\n");
        BuildDataSection(sb);
        RenderCode(sb);

        // Phase 8: Collect constants for ApplyConstantValues
        var constants = new List<(string Id, string UdonType, object Value)>();
        foreach (var v in _vars)
            if (v.ConstValue != null)
                constants.Add((v.Id, v.UdonType, v.ConstValue));

        return new CodeGenResult
        {
            Uasm = sb.ToString(),
            HeapSize = (uint)(_vars.Count + _externs.Count),
            Constants = constants,
        };
    }

    // ── Variable declarations ──

    void EmitReflectionVars()
    {
        // Only the return jump infrastructure var is created by CodeGen.
        // __refl_typeid, __refl_typename, etc. come from IrModule.Fields.
        DeclareVar("__intnl_returnJump_SystemUInt32_0", "SystemUInt32", "0xFFFFFFFF", VarFlags.None);
    }

    void DeclareField(FieldDecl field)
    {
        var flags = VarFlags.None;
        if ((field.Flags & FieldFlags.Export) != 0) flags |= VarFlags.Export;
        if ((field.Flags & FieldFlags.Sync) != 0) flags |= VarFlags.Sync;

        // "this" is a special UASM assembler directive that must appear in the data section.
        // It is NOT a runtime constant to apply via ApplyConstantValues.
        string dataDefault = null;
        object constValue = field.DefaultValue;
        if (constValue is string s && s == "this")
        {
            dataDefault = "this";
            constValue = null;
        }

        DeclareVar(field.Name, field.Type, dataDefault, flags, field.SyncMode, constValue);
    }

    void DeclareVar(string id, string udonType, string defaultValue, VarFlags flags,
        string syncMode = null, object constValue = null)
    {
        if (!_declaredVarIds.Add(id)) return; // Skip duplicates
        _vars.Add(new VarDecl
        {
            Id = id,
            UdonType = udonType,
            DefaultValue = defaultValue,
            Flags = flags,
            SyncMode = syncMode,
            ConstValue = constValue,
        });
    }

    /// <summary>Get or create a UASM variable for a VReg.</summary>
    string GetVRegVar(VReg reg)
    {
        if (_vregVars.TryGetValue(reg.Id, out var existing))
            return existing;
        var id = $"__intnl_{reg.Type}_{reg.Id}";
        _vregVars[reg.Id] = id;
        DeclareVar(id, reg.Type, null, VarFlags.None);
        return id;
    }

    /// <summary>Get or create a UASM variable for an IrConst.</summary>
    string GetConstVar(IrConst c)
    {
        var valueStr = FormatConstValue(c.Value);
        var key = $"{c.Type}_{valueStr}";
        if (_constPool.TryGetValue(key, out var existing))
            return existing;
        var id = $"__const_{c.Type}_{_constIdx++}";
        _constPool[key] = id;
        DeclareVar(id, c.Type, null, VarFlags.None, constValue: c.Value);
        return id;
    }

    /// <summary>Resolve an IrValue to a UASM variable ID.</summary>
    string ResolveValue(IrValue val)
    {
        return val switch
        {
            VReg reg => GetVRegVar(reg),
            IrConst c => GetConstVar(c),
            IrFuncRef fr => GetFuncRefVar(fr),
            _ => throw new InvalidOperationException($"Unknown IrValue type: {val.GetType().Name}")
        };
    }

    /// <summary>Get or create a const variable for a function entry address.</summary>
    string GetFuncRefVar(IrFuncRef fr)
    {
        if (_funcRefVars.TryGetValue(fr.Target.Name, out var existing))
            return existing;
        var varName = $"__const_funcaddr_SystemUInt32_{_funcRefIdx++}";
        // Resolve to body label (skip sentinel) for exported functions, or entry label for internal
        var targetLabel = fr.Target.ExportName != null
            ? $"{fr.Target.Name}__body"
            : _blockLabels[fr.Target.Entry];
        _funcRefConsts.Add((varName, targetLabel));
        _funcRefVars[fr.Target.Name] = varName;
        return varName;
    }

    static string FormatConstValue(object value)
    {
        if (value == null) return "null";
        if (value is float f) return f.ToString("R", CultureInfo.InvariantCulture);
        if (value is double d) return d.ToString("R", CultureInfo.InvariantCulture);
        if (value is bool b) return b ? "True" : "False";
        if (value is string s) return s;
        if (value is IFormattable fmt) return fmt.ToString(null, CultureInfo.InvariantCulture);
        return value.ToString();
    }

    // ── Function preparation ──

    void PrepareFunction(IrFunction func)
    {
        foreach (var block in func.Blocks)
        {
            string labelName;
            if (block == func.Entry)
                labelName = func.ExportName ?? $"__{func.Name}";
            else if (block.Hint != null)
                labelName = block.Hint;
            else
                labelName = $"__{func.Name}_bb{block.Id}";
            _blockLabels[block] = labelName;
        }

        for (int i = 0; i < func.Parameters.Count; i++)
        {
            var (name, type) = func.Parameters[i];
            DeclareVar(name, type, null, VarFlags.None);
        }

        if (func.ReturnType != null)
        {
            var retId = func.ReturnVarId ?? $"__{func.Name}__ret";
            DeclareVar(retId, func.ReturnType, null, VarFlags.None);
        }

        foreach (var block in func.Blocks)
            foreach (var inst in block.Insts)
                if (inst.Dest != null)
                    GetVRegVar(inst.Dest);
    }

    // ── Block linearization ──

    static List<IrBlock> ComputeRPO(IrFunction func)
    {
        var visited = new HashSet<int>();
        var postorder = new List<IrBlock>();
        Visit(func.Entry, visited, postorder);
        postorder.Reverse();
        return postorder;

        static void Visit(IrBlock block, HashSet<int> visited, List<IrBlock> postorder)
        {
            if (!visited.Add(block.Id)) return;
            foreach (var succ in block.Successors)
                Visit(succ, visited, postorder);
            postorder.Add(block);
        }
    }

    // ── Code entry helpers ──

    void AddPush(string varId) =>
        _code.Add(new CodeLine { Kind = CodeKind.Push, Operand = varId });

    void AddCopy() =>
        _code.Add(new CodeLine { Kind = CodeKind.Copy });

    void AddJump(string targetLabel) =>
        _code.Add(new CodeLine { Kind = CodeKind.Jump, Operand = targetLabel });

    void AddJumpIfFalse(string targetLabel) =>
        _code.Add(new CodeLine { Kind = CodeKind.JumpIfFalse, Operand = targetLabel });

    void AddJumpIndirect(string varId) =>
        _code.Add(new CodeLine { Kind = CodeKind.JumpIndirect, Operand = varId });

    void AddExtern(string sig)
    {
        _code.Add(new CodeLine { Kind = CodeKind.Extern, Operand = sig });
        _externs.Add(sig);
    }

    void AddLabel(string name) =>
        _code.Add(new CodeLine { Kind = CodeKind.Label, LabelName = name });

    void AddExport(string name) =>
        _code.Add(new CodeLine { Kind = CodeKind.Export, LabelName = name });

    /// <summary>Emit PUSH src, PUSH dst, COPY (skip if src == dst).</summary>
    void AddCopyPair(string src, string dst)
    {
        if (src == dst) return;
        AddPush(src);
        AddPush(dst);
        AddCopy();
    }

    // ── Function emission (pass 1: collect code entries) ──

    void EmitFunction(IrFunction func)
    {
        var rpo = ComputeRPO(func);

        if (func.ExportName != null)
        {
            AddExport(func.ExportName);
            AddLabel(_blockLabels[func.Entry]);
            // Sentinel: PUSH 0xFFFFFFFF (halt marker for return to Udon VM)
            AddPush("__intnl_returnJump_SystemUInt32_0");
            // Body label: internal calls jump here to skip sentinel
            AddLabel($"{func.Name}__body");
        }
        else
        {
            AddLabel(_blockLabels[func.Entry]);
        }

        for (int bi = 0; bi < rpo.Count; bi++)
        {
            var block = rpo[bi];
            var nextBlock = bi + 1 < rpo.Count ? rpo[bi + 1] : null;

            if (block != func.Entry)
                AddLabel(_blockLabels[block]);

            foreach (var inst in block.Insts)
                EmitInst(inst, func, nextBlock);
        }
    }

    void EmitInst(IrInst inst, IrFunction func, IrBlock nextBlock)
    {
        switch (inst)
        {
            case CallExtern call:
                EmitCallExtern(call);
                break;

            case CallInternal call:
                EmitCallInternal(call, func);
                break;

            case CallIndirect call:
                EmitCallIndirect(call, func);
                break;

            case LoadField load:
                AddCopyPair(load.FieldName, GetVRegVar(load.Result));
                break;

            case StoreField store:
                AddCopyPair(ResolveValue(store.Value), store.FieldName);
                break;

            case Select sel:
                EmitSelect(sel, func);
                break;

            case Phi _:
                throw new InvalidOperationException("Phi nodes must be eliminated before CodeGen");

            case Copy copy:
                AddCopyPair(ResolveValue(copy.Source), GetVRegVar(copy.Result));
                break;

            case Jump jump:
                if (jump.Target != nextBlock)
                    AddJump(_blockLabels[jump.Target]);
                break;

            case Branch branch:
                EmitBranch(branch, nextBlock);
                break;

            case Return ret:
                EmitReturn(ret, func);
                break;

            case Unreachable:
                break;

            default:
                throw new InvalidOperationException($"Unknown IR instruction: {inst.GetType().Name}");
        }
    }

    void EmitCallExtern(CallExtern call)
    {
        foreach (var arg in call.Args)
            AddPush(ResolveValue(arg));
        if (call.Result != null)
            AddPush(GetVRegVar(call.Result));
        AddExtern(call.ExternSig);
    }

    void EmitCallInternal(CallInternal call, IrFunction callerFunc)
    {
        var target = call.Target;
        for (int i = 0; i < call.Args.Length && i < target.Parameters.Count; i++)
            AddCopyPair(ResolveValue(call.Args[i]), target.Parameters[i].Name);

        var retLabel = $"__{callerFunc.Name}__callret_{_retaddrIdx}";
        var retaddrVar = $"__const_retaddr_SystemUInt32_{_retaddrIdx}";
        _retaddrIdx++;
        _retaddrConsts.Add((retaddrVar, retLabel));

        AddPush(retaddrVar);

        var bodyLabel = target.ExportName != null
            ? $"{target.Name}__body"
            : _blockLabels[target.Entry];
        AddJump(bodyLabel);

        AddLabel(retLabel);

        if (call.Result != null && target.ReturnType != null)
        {
            var retVarId = target.ReturnVarId ?? $"__{target.Name}__ret";
            AddCopyPair(retVarId, GetVRegVar(call.Result));
        }
    }

    void EmitCallIndirect(CallIndirect call, IrFunction callerFunc)
    {
        // Copy args to convention fields
        for (int i = 0; i < call.Args.Length && i < call.ArgFields.Length; i++)
            AddCopyPair(ResolveValue(call.Args[i]), call.ArgFields[i]);

        // Copy method pointer to temp (must precede retaddr PUSH to keep stack balanced for COPY)
        var ptrVar = ResolveValue(call.MethodPtr);
        var tempVar = $"__intnl_dlgptr_SystemUInt32_{_dlgTempIdx++}";
        DeclareVar(tempVar, "SystemUInt32", null, VarFlags.None);
        AddCopyPair(ptrVar, tempVar);

        // Push return address onto stack, then jump through temp
        var retLabel = $"__{callerFunc.Name}__callret_{_retaddrIdx}";
        var retaddrVar = $"__const_retaddr_SystemUInt32_{_retaddrIdx}";
        _retaddrIdx++;
        _retaddrConsts.Add((retaddrVar, retLabel));
        AddPush(retaddrVar);
        AddJumpIndirect(tempVar);

        // Return point
        AddLabel(retLabel);

        // Copy return value from convention field
        if (call.Result != null && call.RetField != null)
            AddCopyPair(call.RetField, GetVRegVar(call.Result));
    }

    void EmitSelect(Select sel, IrFunction func)
    {
        var destVar = GetVRegVar(sel.Result);
        var falseLabel = $"__{func.Name}__sel_f_{sel.Result.Id}";
        var endLabel = $"__{func.Name}__sel_e_{sel.Result.Id}";

        AddPush(ResolveValue(sel.Cond));
        AddJumpIfFalse(falseLabel);

        // true path
        AddCopyPair(ResolveValue(sel.TrueValue), destVar);
        AddJump(endLabel);

        // false path
        AddLabel(falseLabel);
        AddCopyPair(ResolveValue(sel.FalseValue), destVar);

        // end
        AddLabel(endLabel);
    }

    void EmitBranch(Branch branch, IrBlock nextBlock)
    {
        AddPush(ResolveValue(branch.Cond));

        if (branch.TrueTarget == nextBlock)
        {
            // JIF to false target, fall through to true target (next block)
            AddJumpIfFalse(_blockLabels[branch.FalseTarget]);
        }
        else
        {
            // JIF to false target, then JUMP to true target
            AddJumpIfFalse(_blockLabels[branch.FalseTarget]);
            AddJump(_blockLabels[branch.TrueTarget]);
        }
    }

    void EmitReturn(Return ret, IrFunction func)
    {
        if (ret.Value != null && func.ReturnType != null)
        {
            var retVarId = func.ReturnVarId ?? $"__{func.Name}__ret";
            AddCopyPair(ResolveValue(ret.Value), retVarId);
        }

        AddPush("__intnl_returnJump_SystemUInt32_0");
        AddCopy();
        AddJumpIndirect("__intnl_returnJump_SystemUInt32_0");
    }

    // ── Address computation (pass 2) ──

    void ComputeAddresses()
    {
        uint addr = 0;
        foreach (var line in _code)
        {
            if (line.Kind == CodeKind.Label && line.LabelName != null)
                _labelAddrs[line.LabelName] = addr;
            addr += GetSize(line.Kind);
        }
    }

    // ── Code rendering ──

    void RenderCode(StringBuilder sb)
    {
        sb.Append(".code_start\n");
        // Track which addresses already have an emitted label to avoid aliasing.
        // Jump addresses are numeric so skipped labels don't affect correctness.
        var emittedLabelAddrs = new HashSet<uint>();
        bool afterExport = false;
        foreach (var line in _code)
        {
            switch (line.Kind)
            {
                case CodeKind.Push:
                    sb.Append($"        PUSH, {line.Operand}\n");
                    afterExport = false;
                    break;
                case CodeKind.Copy:
                    sb.Append("        COPY\n");
                    afterExport = false;
                    break;
                case CodeKind.Jump:
                    sb.Append($"        JUMP, 0x{_labelAddrs[line.Operand]:x8}\n");
                    afterExport = false;
                    break;
                case CodeKind.JumpIfFalse:
                    sb.Append($"        JUMP_IF_FALSE, 0x{_labelAddrs[line.Operand]:x8}\n");
                    afterExport = false;
                    break;
                case CodeKind.JumpIndirect:
                    sb.Append($"        JUMP_INDIRECT, {line.Operand}\n");
                    afterExport = false;
                    break;
                case CodeKind.Extern:
                    sb.Append($"        EXTERN, \"{line.Operand}\"\n");
                    afterExport = false;
                    break;
                case CodeKind.Label:
                    var addr = _labelAddrs[line.LabelName];
                    // Always emit label after .export; otherwise skip duplicates
                    if (afterExport)
                    {
                        emittedLabelAddrs.Add(addr);
                        sb.Append($"    {line.LabelName}:\n");
                    }
                    else if (emittedLabelAddrs.Add(addr))
                    {
                        sb.Append($"    {line.LabelName}:\n");
                    }
                    afterExport = false;
                    break;
                case CodeKind.Export:
                    sb.Append($"    .export {line.LabelName}\n");
                    afterExport = true;
                    break;
            }
        }
        sb.Append(".code_end\n");
    }

    // ── Data section ──

    void BuildDataSection(StringBuilder sb)
    {
        sb.Append(".data_start\n");

        foreach (var v in _vars)
            if ((v.Flags & VarFlags.Export) != 0)
                sb.Append($"    .export {v.Id}\n");

        foreach (var v in _vars)
            if ((v.Flags & VarFlags.Sync) != 0)
                sb.Append($"    .sync {v.Id}, {v.SyncMode ?? "none"}\n");

        foreach (var v in _vars)
        {
            var def = v.DefaultValue ?? "null";
            sb.Append($"    {v.Id}: %{v.UdonType}, {def}\n");
        }

        sb.Append(".data_end\n");
    }
}
