using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

/// <summary>
/// Generates UASM assembly text from an LModule (LIR).
/// Two-pass approach:
///   Pass 1: Collect instructions into intermediate representation, compute label addresses.
///   Pass 2: Render UASM text with resolved numeric addresses.
/// </summary>
public static class LirToUasm
{
    public static CodeGenResult Generate(LModule module)
    {
        var gen = new Generator(module);
        return gen.Run();
    }

    // ── Intermediate code representation ──

    enum CodeKind
    {
        Push,           // 8 bytes
        Copy,           // 4 bytes
        Jump,           // 8 bytes — operand = target label
        JumpIfFalse,    // 8 bytes — operand = target label
        JumpIndirect,   // 8 bytes — operand = var name
        Extern,         // 8 bytes — operand = extern signature
        Label,          // 0 bytes
        Export,         // 0 bytes
    }

    struct CodeLine
    {
        public CodeKind Kind;
        public string Operand;
        public string LabelName;
    }

    static uint GetSize(CodeKind kind) => kind switch
    {
        CodeKind.Push => 8,
        CodeKind.Copy => 4,
        CodeKind.Jump => 8,
        CodeKind.JumpIfFalse => 8,
        CodeKind.JumpIndirect => 8,
        CodeKind.Extern => 8,
        _ => 0,
    };

    sealed class Generator
    {
        readonly LModule _module;
        readonly List<VarDecl> _vars = new();
        readonly Dictionary<string, string> _declaredVarTypes = new();  // id → udonType
        readonly HashSet<string> _externs = new();
        readonly Dictionary<string, string> _constPool = new();     // "type_value" → varId
        readonly Dictionary<string, LFunction> _funcByName = new();

        // Slot → UASM variable name: keyed by (funcIndex, slotId) for global uniqueness.
        readonly Dictionary<(int funcIdx, int slotId), string> _slotVars = new();

        // Block label: keyed by (funcIndex, blockId).
        readonly Dictionary<(int funcIdx, int blockId), string> _blockLabels = new();

        // Two-pass infrastructure
        readonly List<CodeLine> _code = new();
        readonly Dictionary<string, uint> _labelAddrs = new();
        readonly List<(string VarName, string LabelName)> _retaddrConsts = new();
        readonly List<(string VarName, string LabelName)> _funcRefConsts = new();
        readonly Dictionary<string, string> _funcRefVars = new();

        int _constIdx;
        int _retaddrIdx;
        int _intnlIdx;
        int _funcRefIdx;

        struct VarDecl
        {
            public string Id, UdonType, DefaultValue;
            public VarFlags Flags;
            public string SyncMode;
            public object ConstValue;
        }

        public Generator(LModule module)
        {
            _module = module;
            foreach (var func in module.Functions)
                _funcByName[func.Name] = func;
        }

        public CodeGenResult Run()
        {
            // Phase 1: Infrastructure variable
            DeclareVar("__intnl_returnJump_SystemUInt32_0", "SystemUInt32", "0xFFFFFFFF", VarFlags.None);

            // Phase 2: Field declarations
            foreach (var field in _module.Fields)
                DeclareField(field);

            // Phase 3: Assign labels to blocks and allocate slot variables
            for (int fi = 0; fi < _module.Functions.Count; fi++)
                PrepareFunction(fi, _module.Functions[fi]);

            // Phase 4: Collect code entries
            for (int fi = 0; fi < _module.Functions.Count; fi++)
                EmitFunction(fi, _module.Functions[fi]);

            // Phase 5: Compute label addresses
            ComputeAddresses();

            // Phase 6: Resolve retaddr constants
            foreach (var (varName, labelName) in _retaddrConsts)
            {
                var addr = _labelAddrs[labelName];
                DeclareVar(varName, "SystemUInt32", null, VarFlags.None, constValue: addr);
            }

            // Phase 6b: Resolve funcref constants
            foreach (var (varName, labelName) in _funcRefConsts)
            {
                var addr = _labelAddrs[labelName];
                DeclareVar(varName, "SystemUInt32", null, VarFlags.None, constValue: addr);
            }

            // Phase 7: Build output
            var sb = new StringBuilder();
            sb.Append("# Generated by USugar\n");
            BuildDataSection(sb);
            RenderCode(sb);

            // Phase 8: Collect constants
            var constants = new List<(string Id, string UdonType, object Value)>();
            foreach (var v in _vars)
                if (v.ConstValue != null)
                    constants.Add((v.Id, v.UdonType, v.ConstValue));

            return new CodeGenResult
            {
                Uasm = sb.ToString(),
                HeapSize = (uint)(_vars.Count + _externs.Count),
                Constants = constants,
            };
        }

        // ── Variable declarations ──

        void DeclareField(FieldDecl field)
        {
            var flags = VarFlags.None;
            if ((field.Flags & FieldFlags.Export) != 0) flags |= VarFlags.Export;
            if ((field.Flags & FieldFlags.Sync) != 0) flags |= VarFlags.Sync;

            string dataDefault = null;
            object constValue = field.DefaultValue;
            if (constValue is string s && s == "this")
            {
                dataDefault = "this";
                constValue = null;
            }

            DeclareVar(field.Name, field.Type, dataDefault, flags, field.SyncMode, constValue);
        }

        void DeclareVar(string id, string udonType, string defaultValue, VarFlags flags,
            string syncMode = null, object constValue = null)
        {
            if (_declaredVarTypes.TryGetValue(id, out var existingType))
            {
                if (existingType != udonType)
                    throw new InvalidOperationException(
                        $"Variable '{id}' declared with conflicting types: '{existingType}' vs '{udonType}'");
                return;
            }
            _declaredVarTypes[id] = udonType;
            _vars.Add(new VarDecl
            {
                Id = id,
                UdonType = udonType,
                DefaultValue = defaultValue,
                Flags = flags,
                SyncMode = syncMode,
                ConstValue = constValue,
            });
        }

        // ── Slot → variable name mapping ──

        string GetSlotVar(int funcIdx, int slotId, LFunction func)
        {
            var key = (funcIdx, slotId);
            if (_slotVars.TryGetValue(key, out var existing))
                return existing;

            var slot = func.Slots[slotId];
            string id;
            if (slot.Class == SlotClass.Pinned && slot.FixedName != null)
            {
                id = slot.FixedName;
            }
            else
            {
                id = $"__intnl_{slot.Type}_{_intnlIdx++}";
                DeclareVar(id, slot.Type, null, VarFlags.None);
            }

            _slotVars[key] = id;
            return id;
        }

        // ── Operand resolution ──

        string ResolveOperand(LOperand op, int funcIdx, LFunction func)
        {
            return op switch
            {
                LSlotRef slot => GetSlotVar(funcIdx, slot.SlotId, func),
                LConst c => GetConstVar(c),
                LFieldRef f => f.FieldName,
                LFuncRef fr => GetFuncRefVar(fr),
                _ => throw new InvalidOperationException($"Unknown LOperand type: {op.GetType().Name}")
            };
        }

        string GetConstVar(LConst c)
        {
            var valueStr = FormatConstValue(c.Value);
            var key = $"{c.Type}_{valueStr}";
            if (_constPool.TryGetValue(key, out var existing))
                return existing;
            var id = $"__const_{c.Type}_{_constIdx++}";
            _constPool[key] = id;
            DeclareVar(id, c.Type, null, VarFlags.None, constValue: c.Value);
            return id;
        }

        string GetFuncRefVar(LFuncRef fr)
        {
            if (_funcRefVars.TryGetValue(fr.FuncName, out var existing))
                return existing;
            var varName = $"__const_funcaddr_SystemUInt32_{_funcRefIdx++}";

            // Find the target function to determine the right label
            if (!_funcByName.TryGetValue(fr.FuncName, out var target))
                throw new InvalidOperationException($"LFuncRef references unknown function: {fr.FuncName}");

            // For exported functions, jump to body label (skip sentinel)
            var targetLabel = target.ExportName != null
                ? $"{target.Name}__body"
                : _blockLabels[(FindFuncIndex(target), target.Entry.Id)];

            _funcRefConsts.Add((varName, targetLabel));
            _funcRefVars[fr.FuncName] = varName;
            return varName;
        }

        int FindFuncIndex(LFunction func)
        {
            for (int i = 0; i < _module.Functions.Count; i++)
                if (_module.Functions[i] == func) return i;
            throw new InvalidOperationException($"Function not found in module: {func.Name}");
        }

        static string FormatConstValue(object value)
        {
            if (value == null) return "null";
            if (value is float f) return f.ToString("R", CultureInfo.InvariantCulture);
            if (value is double d) return d.ToString("R", CultureInfo.InvariantCulture);
            if (value is bool b) return b ? "True" : "False";
            if (value is string s) return s;
            if (value is IFormattable fmt) return fmt.ToString(null, CultureInfo.InvariantCulture);
            return value.ToString();
        }

        // ── Function preparation ──

        void PrepareFunction(int funcIdx, LFunction func)
        {
            // Assign block labels
            foreach (var block in func.Blocks)
            {
                string labelName;
                if (block == func.Entry)
                    labelName = func.ExportName ?? $"__{func.Name}";
                else if (block.Hint != null)
                    labelName = block.Hint;
                else
                    labelName = $"__{func.Name}_bb{block.Id}";
                _blockLabels[(funcIdx, block.Id)] = labelName;
            }

            // Pre-allocate slot variables (ensures all are declared before code gen)
            for (int si = 0; si < func.Slots.Count; si++)
                GetSlotVar(funcIdx, si, func);

            // Declare return field variable if needed (may not be in module Fields)
            if (func.ReturnFieldName != null && func.ReturnType != null)
                DeclareVar(func.ReturnFieldName, func.ReturnType, null, VarFlags.None);
        }

        // ── Block linearization (RPO) ──

        static List<LBlock> ComputeRPO(LFunction func)
        {
            var blockById = new Dictionary<int, LBlock>();
            foreach (var b in func.Blocks) blockById[b.Id] = b;

            var visited = new HashSet<int>();
            var postorder = new List<LBlock>();
            Visit(func.Entry, blockById, visited, postorder);
            postorder.Reverse();
            return postorder;

            static void Visit(LBlock block, Dictionary<int, LBlock> blockById,
                HashSet<int> visited, List<LBlock> postorder)
            {
                if (!visited.Add(block.Id)) return;
                if (block.Term != null)
                {
                    foreach (var succId in GetSuccessors(block.Term))
                        if (blockById.TryGetValue(succId, out var succ))
                            Visit(succ, blockById, visited, postorder);
                }
                postorder.Add(block);
            }

            static IEnumerable<int> GetSuccessors(LTerminator term)
            {
                switch (term)
                {
                    case LJump j: yield return j.TargetBlockId; break;
                    case LBranch b: yield return b.TrueBlockId; yield return b.FalseBlockId; break;
                    case LReturn: break;
                }
            }
        }

        // ── Code entry helpers ──

        void AddPush(string varId) =>
            _code.Add(new CodeLine { Kind = CodeKind.Push, Operand = varId });

        void AddCopy() =>
            _code.Add(new CodeLine { Kind = CodeKind.Copy });

        void AddJump(string targetLabel) =>
            _code.Add(new CodeLine { Kind = CodeKind.Jump, Operand = targetLabel });

        void AddJumpIfFalse(string targetLabel) =>
            _code.Add(new CodeLine { Kind = CodeKind.JumpIfFalse, Operand = targetLabel });

        void AddJumpIndirect(string varId) =>
            _code.Add(new CodeLine { Kind = CodeKind.JumpIndirect, Operand = varId });

        void AddExtern(string sig)
        {
            _code.Add(new CodeLine { Kind = CodeKind.Extern, Operand = sig });
            _externs.Add(sig);
        }

        void AddLabel(string name) =>
            _code.Add(new CodeLine { Kind = CodeKind.Label, LabelName = name });

        void AddExport(string name) =>
            _code.Add(new CodeLine { Kind = CodeKind.Export, LabelName = name });

        void AddCopyPair(string src, string dst)
        {
            if (src == dst) return;
            AddPush(src);
            AddPush(dst);
            AddCopy();
        }

        // ── Function emission ──

        void EmitFunction(int funcIdx, LFunction func)
        {
            var rpo = ComputeRPO(func);

            if (func.ExportName != null)
            {
                AddExport(func.ExportName);
                AddLabel(_blockLabels[(funcIdx, func.Entry.Id)]);
                // Sentinel: push 0xFFFFFFFF onto stack. The callee's RET will POP
                // this into returnJump, causing JUMP_INDIRECT to halt (address > program size).
                var sentinelVar = "__const_SystemUInt32_sentinel";
                DeclareVar(sentinelVar, "SystemUInt32", null, VarFlags.None, constValue: 0xFFFFFFFF);
                AddPush(sentinelVar);
                AddLabel($"{func.Name}__body");
            }
            else
            {
                AddLabel(_blockLabels[(funcIdx, func.Entry.Id)]);
            }

            for (int bi = 0; bi < rpo.Count; bi++)
            {
                var block = rpo[bi];
                var nextBlock = bi + 1 < rpo.Count ? rpo[bi + 1] : null;

                if (block != func.Entry)
                    AddLabel(_blockLabels[(funcIdx, block.Id)]);

                foreach (var inst in block.Insts)
                    EmitInst(inst, funcIdx, func);

                if (block.Term != null)
                    EmitTerminator(block.Term, funcIdx, func, nextBlock);
            }
        }

        void EmitInst(LInst inst, int funcIdx, LFunction func)
        {
            switch (inst)
            {
                case LMove move:
                    EmitMove(move, funcIdx, func);
                    break;

                case LLoadField load:
                    AddCopyPair(load.FieldName, GetSlotVar(funcIdx, load.DestSlot, func));
                    break;

                case LStoreField store:
                    AddCopyPair(ResolveOperand(store.Value, funcIdx, func), store.FieldName);
                    break;

                case LCallExtern call:
                    EmitCallExtern(call, funcIdx, func);
                    break;

                case LCallInternal call:
                    EmitCallInternal(call, funcIdx, func);
                    break;

                default:
                    throw new InvalidOperationException($"Unknown LInst type: {inst.GetType().Name}");
            }
        }

        void EmitMove(LMove move, int funcIdx, LFunction func)
        {
            var src = ResolveOperand(move.Src, funcIdx, func);
            var dst = GetSlotVar(funcIdx, move.DestSlot, func);
            AddCopyPair(src, dst);
        }

        void EmitCallExtern(LCallExtern call, int funcIdx, LFunction func)
        {
            foreach (var arg in call.Args)
                AddPush(ResolveOperand(arg, funcIdx, func));
            if (call.DestSlot.HasValue)
                AddPush(GetSlotVar(funcIdx, call.DestSlot.Value, func));
            AddExtern(call.Sig);
        }

        void EmitCallInternal(LCallInternal call, int funcIdx, LFunction func)
        {
            // __indirect is a special marker for delegate invocation via JUMP_INDIRECT.
            // Args have been stored to convention fields by the handler; the single
            // arg here is the method pointer (SystemUInt32 address).
            if (call.FuncName == "__indirect")
            {
                EmitCallIndirect(call, funcIdx, func);
                return;
            }

            if (!_funcByName.TryGetValue(call.FuncName, out var target))
                throw new InvalidOperationException($"LCallInternal references unknown function: {call.FuncName}");

            // Copy args to param fields
            for (int i = 0; i < call.Args.Count && i < target.ParamFieldNames.Count; i++)
                AddCopyPair(ResolveOperand(call.Args[i], funcIdx, func), target.ParamFieldNames[i]);

            // Push return address and jump
            var retLabel = $"__{func.Name}__callret_{_retaddrIdx}";
            var retaddrVar = $"__const_retaddr_SystemUInt32_{_retaddrIdx}";
            _retaddrIdx++;
            _retaddrConsts.Add((retaddrVar, retLabel));

            // Push return address onto stack (callee's RET will POP it)
            AddPush(retaddrVar);

            var targetFuncIdx = FindFuncIndex(target);
            var bodyLabel = target.ExportName != null
                ? $"{target.Name}__body"
                : _blockLabels[(targetFuncIdx, target.Entry.Id)];
            AddJump(bodyLabel);

            AddLabel(retLabel);

            // Copy return value if needed
            if (call.DestSlot.HasValue && target.ReturnFieldName != null)
                AddCopyPair(target.ReturnFieldName, GetSlotVar(funcIdx, call.DestSlot.Value, func));
        }

        void EmitCallIndirect(LCallInternal call, int funcIdx, LFunction func)
        {
            // The single arg is the method pointer
            if (call.Args.Count < 1)
                throw new InvalidOperationException("__indirect call requires at least one arg (method pointer)");

            var ptrVar = ResolveOperand(call.Args[0], funcIdx, func);

            // Copy method pointer to a temp to keep stack balanced
            var tempVar = $"__intnl_dlgptr_SystemUInt32_{_intnlIdx++}";
            DeclareVar(tempVar, "SystemUInt32", null, VarFlags.None);
            AddCopyPair(ptrVar, tempVar);

            // Push return address and jump indirect
            var retLabel = $"__{func.Name}__callret_{_retaddrIdx}";
            var retaddrVar = $"__const_retaddr_SystemUInt32_{_retaddrIdx}";
            _retaddrIdx++;
            _retaddrConsts.Add((retaddrVar, retLabel));

            AddPush(retaddrVar);
            AddJumpIndirect(tempVar);

            AddLabel(retLabel);

            // No return value copy — the handler reads it via LoadField from convention fields
        }

        void EmitTerminator(LTerminator term, int funcIdx, LFunction func, LBlock nextBlock)
        {
            switch (term)
            {
                case LJump jump:
                    if (nextBlock == null || jump.TargetBlockId != nextBlock.Id)
                        AddJump(_blockLabels[(funcIdx, jump.TargetBlockId)]);
                    break;

                case LBranch branch:
                    EmitBranch(branch, funcIdx, func, nextBlock);
                    break;

                case LReturn ret:
                    EmitReturn(ret, funcIdx, func);
                    break;

                default:
                    throw new InvalidOperationException($"Unknown LTerminator type: {term.GetType().Name}");
            }
        }

        void EmitBranch(LBranch branch, int funcIdx, LFunction func, LBlock nextBlock)
        {
            AddPush(ResolveOperand(branch.Cond, funcIdx, func));

            if (nextBlock != null && branch.TrueBlockId == nextBlock.Id)
            {
                // Fall through to true, jump to false
                AddJumpIfFalse(_blockLabels[(funcIdx, branch.FalseBlockId)]);
            }
            else
            {
                AddJumpIfFalse(_blockLabels[(funcIdx, branch.FalseBlockId)]);
                AddJump(_blockLabels[(funcIdx, branch.TrueBlockId)]);
            }
        }

        void EmitReturn(LReturn ret, int funcIdx, LFunction func)
        {
            if (ret.Value != null && func.ReturnFieldName != null)
                AddCopyPair(ResolveOperand(ret.Value, funcIdx, func), func.ReturnFieldName);

            // Stack-based return protocol: POP return address from stack into returnJump, then jump.
            // The caller (or sentinel preamble) pushed the return address onto the stack.
            AddPush("__intnl_returnJump_SystemUInt32_0");
            AddCopy();
            AddJumpIndirect("__intnl_returnJump_SystemUInt32_0");
        }

        // ── Address computation ──

        void ComputeAddresses()
        {
            uint addr = 0;
            foreach (var line in _code)
            {
                if (line.Kind == CodeKind.Label && line.LabelName != null)
                    _labelAddrs[line.LabelName] = addr;
                addr += GetSize(line.Kind);
            }
        }

        // ── Code rendering ──

        void RenderCode(StringBuilder sb)
        {
            sb.Append(".code_start\n");
            var emittedLabelAddrs = new HashSet<uint>();
            bool afterExport = false;
            foreach (var line in _code)
            {
                switch (line.Kind)
                {
                    case CodeKind.Push:
                        sb.Append($"        PUSH, {line.Operand}\n");
                        afterExport = false;
                        break;
                    case CodeKind.Copy:
                        sb.Append("        COPY\n");
                        afterExport = false;
                        break;
                    case CodeKind.Jump:
                        sb.Append($"        JUMP, 0x{_labelAddrs[line.Operand]:x8}\n");
                        afterExport = false;
                        break;
                    case CodeKind.JumpIfFalse:
                        sb.Append($"        JUMP_IF_FALSE, 0x{_labelAddrs[line.Operand]:x8}\n");
                        afterExport = false;
                        break;
                    case CodeKind.JumpIndirect:
                        sb.Append($"        JUMP_INDIRECT, {line.Operand}\n");
                        afterExport = false;
                        break;
                    case CodeKind.Extern:
                        sb.Append($"        EXTERN, \"{line.Operand}\"\n");
                        afterExport = false;
                        break;
                    case CodeKind.Label:
                        var addr = _labelAddrs[line.LabelName];
                        if (afterExport)
                        {
                            emittedLabelAddrs.Add(addr);
                            sb.Append($"    {line.LabelName}:\n");
                        }
                        else if (emittedLabelAddrs.Add(addr))
                        {
                            sb.Append($"    {line.LabelName}:\n");
                        }
                        afterExport = false;
                        break;
                    case CodeKind.Export:
                        sb.Append($"    .export {line.LabelName}\n");
                        afterExport = true;
                        break;
                }
            }
            sb.Append(".code_end\n");
        }

        // ── Data section ──

        void BuildDataSection(StringBuilder sb)
        {
            sb.Append(".data_start\n");

            foreach (var v in _vars)
                if ((v.Flags & VarFlags.Export) != 0)
                    sb.Append($"    .export {v.Id}\n");

            foreach (var v in _vars)
                if ((v.Flags & VarFlags.Sync) != 0)
                    sb.Append($"    .sync {v.Id}, {v.SyncMode ?? "none"}\n");

            foreach (var v in _vars)
            {
                var def = v.DefaultValue ?? "null";
                sb.Append($"    {v.Id}: %{v.UdonType}, {def}\n");
            }

            sb.Append(".data_end\n");
        }
    }
}
